---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_ID'] %>
  security_group_ids: ["<%= ENV['AWS_SECURITY_GROUP_ID'] %>"]
  region: <%= ENV['AWS_DEFAULT_REGION'] %>
  availability_zone: <%= ENV['AWS_AVAILABILITY_ZONE'] %>
  subnet_id: <%= ENV['AWS_SUBNET_ID'] %>
  associate_public_ip: true
  require_chef_omnibus: true
  instance_type: m3.medium
  interface: dns
  tags: 
    Name: "uhostchef11server-test-kitchen"

transport:
  ssh_key: <%= File.expand_path(ENV['AWS_SSH_KEY']) %>
  connection_timeout: 10
  connection_retries: 5
  username: ubuntu

driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  client_rb:
    node_name: "localtest.getuhost.org"
    environment: _default
  attributes:
    openssh:
      server:
        password_authentication: 'yes'
        permit_root_login: 'yes'
    cloud:
      public_ipv4: '127.0.0.1'
    authorization:
      sudo:
        users: ['ubuntu']
        passwordless: true

platforms:
  - name: ubuntu-14.04
    driver:
      image_id: ami-bbd5c08b

suites:
  - name: default
    data_bags_path: "test/integration/default/data_bags"
    encrypted_data_bag_secret_key_path: "test/integration/default/encrypted_data_bag_secret"
    run_list:
      - recipe[uhostchef11server::default] 
    attributes:
      chef11server:
        nginx:
          certificate: "localtest.getuhost.org"
